default_stages:
  - commit
exclude: node_modules|.git|.tox
fail_fast: true
repos:
  - hooks:
      - id: detect-secrets
        args: [ '--baseline', '.secrets.baseline' ]
        exclude: (config/settings/test.py|/static|.html|local|README.md|poetry.lock|infra/environments/.*_cf_parameters.json*)
    repo: https://github.com/Yelp/detect-secrets.git
    rev: v1.4.0

  - hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-added-large-files
        args: ['--maxkb=600']
      - id: check-docstring-first
      - id: check-case-conflict
      - id: check-builtin-literals
      - id: mixed-line-ending
      - id: check-json
        files: \.(json)$
      - id: check-toml
        files: \.(toml)$
      - id: fix-encoding-pragma
        args: [ --remove ]
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0

  - hooks:
      - id: isort
        entry: isort
        additional_dependencies: [ "toml" ]
    repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1


  - hooks:
      - exclude: (/settings/)
        id: black
        require_serial: true
        types:
          - python
    repo: https://github.com/ambv/black
    rev: 23.1.0

  - hooks:
      - id: flakeheaven
    repo: https://github.com/flakeheaven/flakeheaven
    rev: 3.2.1

  - hooks:
      - entry: pylint --jobs=0
        exclude: (/settings/)
        files: \.py$
        id: PyLint
        language: system
        name: PyLint
    repo: local

  - hooks:
      - id: commitizen
        stages:
          - commit-msg
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.0

  - hooks:
      - id: bandit
        args: [ --verbose, -ll, --recursive, --exclude, "./venv", . ]
    repo: https://github.com/PyCQA/bandit
    rev: 1.7.4

  - repo: https://github.com/Trim21/poetry-check-lock.git
    rev: v0.0.5
    hooks:
      - id: poetry-check-lock
